# Generated by Django 4.2.4 on 2025-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarmer', '0004_farmerprofile_latitude_farmerprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Quantity in kilograms (kg)'),
        ),
    ]
