# Generated by Django 5.1.6 on 2025-03-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfarmer', '0008_productrequest_delete_priceprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
